apiVersion: modules.kubeform.com/v1alpha1
kind: RDS
metadata:
  name: test-rds
spec:
  providerRef: 
    name: "aws"
  secretRef:
    name: "rds-pass"
  identifier: "demodb"
  engine: "mysql"
  engineVersion: "5.7.19"
  instanceClass: "db.t2.large"
  allocatedStorage: "5"
  storageEncrypted: false
  name: "demodb"
  username: "user"
  port: "3306"
  vpcSecurityGroupIDS: 
    - <vpc security group ID>
  maintenanceWindow: "Mon:00:00-Mon:03:00"
  backupWindow: "03:00-04:00"
  subnetIDS: 
    - <Subnet ID>
  family: "mysql5.7"
  majorEngineVersion: "5.7"
  skipFinalSnapshot: true
  deletionProtection: false
  tags: 
    Owner: "user"
    Environment: "dev"
  parameters:
    - name: "character_set_client"
      value: "utf8"
    - name: "character_set_server"
      value: "utf8"
  options:
     - option_name: "MARIADB_AUDIT_PLUGIN"
       option_settings:
         - name: "SERVER_AUDIT_EVENTS"
           value: "CONNECT"
         - name: "SERVER_AUDIT_FILE_ROTATIONS"
           value: "37"